import test from 'node:test'; import assert from 'node:assert/strict'; import {createTestDb} from './harness.js'; import {equivalentRank,compareNumbers,trackingType,matchPredictionToDraw,rebuildSummary,researchStats,deriveFeatures} from '../src/lib/tracking.js';
async function seedPred(db,id='p1',generated='2026-09-20T11:16:00.000Z',nums=[6,13,14,29,33,38]){await db.prepare(`INSERT INTO payments(payment_public_id,plan_code,amount,currency,payment_status) VALUES('pay1','single',300,'jpy','paid')`).run();await db.prepare(`INSERT INTO purchase_intents(intent_public_id,plan_code,claim_token_hash,status,payment_id) VALUES('i1','single','th1','fulfilled',1)`).run();await db.prepare(`INSERT INTO purchase_entitlements(entitlement_public_id,payment_id,purchase_intent_id,allowed_predictions,status,claim_token_hash) VALUES('e1',1,1,1,'consumed','th2')`).run();await db.prepare(`INSERT INTO predictions(prediction_id,display_sequence,draw_number,number_1,number_2,number_3,number_4,number_5,number_6,combination_key,generated_at,payment_id,entitlement_id,prediction_index,plan_code,algorithm_version,previous_hash,record_hash) VALUES(?,1,'PERMANENT_TRACKING',?,?,?,?,?,?,'06-13-14-29-33-38',?,1,1,1,'single','v1','prev','hash')`).bind(id,...nums,generated).run();return await db.prepare(`SELECT * FROM predictions WHERE prediction_id=?`).bind(id).first();}
async function draw(db,id,no,date,nums,bonus){await db.prepare(`INSERT INTO lottery_draws(draw_id,draw_number,draw_date,n1,n2,n3,n4,n5,n6,bonus_number,source) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(id,no,date,...nums,bonus,'official-test').run();return await db.prepare(`SELECT * FROM lottery_draws WHERE draw_id=?`).bind(id).first();}
test('official-equivalent ranks 1-5',()=>{assert.equal(equivalentRank(6,0),'1');assert.equal(equivalentRank(5,1),'2');assert.equal(equivalentRank(5,0),'3');assert.equal(equivalentRank(4,0),'4');assert.equal(equivalentRank(3,0),'5');assert.equal(equivalentRank(2,1),null)});
test('0..6 main matches and bonus',()=>{for(let n=0;n<=6;n++){const pred=[1,2,3,4,5,6], main=[...pred.slice(0,n),...Array.from({length:6-n},(_,i)=>20+i)];const r=compareNumbers(pred,main, n<6?6:43);assert.equal(r.main_match_count,n); if(n<6)assert.equal(r.bonus_match,1)}});
test('boundary separates historical/forward conservatively',()=>{assert.equal(trackingType('2026-09-20T11:16:00Z','2026-09-19'),'historical_backtest');assert.equal(trackingType('2026-09-20T11:16:00Z','2026-09-20'),'historical_backtest');assert.equal(trackingType('2026-09-20T11:16:00Z','2026-09-21'),'forward_tracking')});
test('match is idempotent, elapsed values and summary work',async()=>{const db=createTestDb(),p=await seedPred(db);const d=await draw(db,'d1',2000,'2026-09-21',[6,13,14,20,21,22],43);await matchPredictionToDraw(db,p,d,'2026-09-21T12:00:00Z');await matchPredictionToDraw(db,p,d,'2026-09-21T12:01:00Z');const c=await db.prepare(`SELECT COUNT(*) c FROM prediction_matches`).first();assert.equal(c.c,1);const m=await db.prepare(`SELECT * FROM prediction_matches`).first();assert.equal(m.main_match_count,3);assert.equal(m.equivalent_rank,'5');assert.equal(m.elapsed_days,1);assert.equal(m.elapsed_draws,1);const s=await db.prepare(`SELECT * FROM prediction_tracking_summary`).first();assert.equal(s.checked_draw_count,1);assert.equal(s.first_3plus_draw_id,'d1')});
test('historical never contaminates forward summary/statistics',async()=>{const db=createTestDb(),p=await seedPred(db);const old=await draw(db,'old',1900,'2026-09-19',[6,13,14,29,33,38],1);const future=await draw(db,'future',2000,'2026-09-21',[6,13,20,21,22,23],43);await matchPredictionToDraw(db,p,old);await matchPredictionToDraw(db,p,future);const s=await db.prepare(`SELECT * FROM prediction_tracking_summary`).first();assert.equal(s.checked_draw_count,1);assert.equal(s.best_main_match_count,2);const stats=await researchStats(db);assert.equal(stats.forward.match_6,0);assert.equal(stats.total_comparisons,2)});
test('best and first3plus update from forward only',async()=>{const db=createTestDb(),p=await seedPred(db);for(const x of [['a',2001,'2026-09-21',[6,13,14,20,21,22],43],['b',2002,'2026-09-24',[6,13,14,20,21,29],43]]){const d=await draw(db,...x);await matchPredictionToDraw(db,p,d)}const s=await db.prepare(`SELECT * FROM prediction_tracking_summary`).first();assert.equal(s.best_main_match_count,4);assert.equal(s.best_draw_id,'b');assert.equal(s.first_3plus_draw_id,'a');assert.equal(s.draws_to_best,2)});
test('summary can be rebuilt from evidence',async()=>{const db=createTestDb(),p=await seedPred(db);const d=await draw(db,'d',2001,'2026-09-21',[6,13,14,20,21,29],43);await matchPredictionToDraw(db,p,d);await db.prepare(`DELETE FROM prediction_tracking_summary`).run();await rebuildSummary(db,'p1');const s=await db.prepare(`SELECT * FROM prediction_tracking_summary`).first();assert.equal(s.best_main_match_count,4)});
test('evidence and draws immutable; predictions remain immutable',async()=>{const db=createTestDb(),p=await seedPred(db);const d=await draw(db,'d',2001,'2026-09-21',[6,13,14,20,21,29],43);await matchPredictionToDraw(db,p,d);for(const sql of [`UPDATE lottery_draws SET n1=2 WHERE draw_id='d'`,`DELETE FROM lottery_draws WHERE draw_id='d'`,`UPDATE prediction_matches SET main_match_count=0`,`DELETE FROM prediction_matches`,`UPDATE predictions SET number_1=2 WHERE prediction_id='p1'`])await assert.rejects(()=>db.prepare(sql).run())});
test('generation feature extraction retains research dimensions',()=>{const f=deriveFeatures([6,13,14,29,33,38],'v1');assert.equal(f.sum,133);assert.equal(f.consecutive_pairs,1);assert.equal(f.algorithm_version,'v1');assert.equal(f.low+f.mid+f.high,6)});
test('official historical fixture: LOTO6 draw #1 is classified historical and matched correctly',async()=>{const db=createTestDb(),p=await seedPred(db);const d=await draw(db,'loto6-1',1,'2000-10-05',[2,8,10,13,27,30],39);const r=await matchPredictionToDraw(db,p,d);assert.equal(r.tracking_type,'historical_backtest');assert.equal(r.main_match_count,1);assert.equal(r.bonus_match,0)});
